### ISSUE TITLE
Consider Fira Code support. 

### ISSUE THREAD

**Issue by lozandier** [powerline/fonts#112]
[Fira Code](https://github.com/tonsky/FiraCode) is an extended version of Fira that adds ligatures; considering that Fira Powerline & Fira Mono Powerline already exist, this seems reasonable to consider adding.

**Comment by davidosomething** [comment]
+1

**Comment by paulcoyle** [comment]
+1

**Comment by jaggy** [comment]
+1

**Comment by erubi** [comment]
+1

**Comment by jaggy** [comment]
Fira Code v0.6 now patched for powerline by default. :+1:

**Comment by filipelinhares** [comment]
+1

**Comment by FuriKuri** [comment]
+1

**Comment by Lokaltog** [comment]
Fira Code includes powerline symbols by default.
