### ISSUE TITLE
Consider Roboto Mono support

### ISSUE THREAD

**Issue by sdcnhajmdfvbgdfnhfm** [powerline/fonts#116]
[Roboto Mono on Google Fonts](https://www.google.com/fonts/specimen/Roboto+Mono)

[Roboto Mono on `google/fonts` git repository](https://github.com/google/fonts/tree/master/apache/robotomono)

**Comment by frmendes** [comment]
+1

**Comment by he9lin** [comment]
+1 please

**Comment by t3chguy** [comment]
+1

**Comment by ronakg** [comment]
+1

**Comment by alexluecke** [comment]
For some reason Roboto Mono Light works for me without any additional configuration, but Roboto Mono does not.

**Comment by ronakg** [comment]
@alexluecke Do you mean powerline symbols appear with regular Roboto Mono Light?

**Comment by alexluecke** [comment]
@ronakg Yes. Powerline seems to work fine with Roboto Mono Light.

**Comment by ronakg** [comment]
That's strange. None of the Roboto Mono versions work for me.

**Comment by alexluecke** [comment]
Debian Jessie + Gnome with gnome-terminal or vim-gtk here.

**Comment by markmcd** [comment]
Thank you @aeroevan! That works a treat.
