### ISSUE TITLE
Windows install script

### ISSUE THREAD

**Issue by ehartford** [powerline/fonts#124]
How to install in Windows?

**Comment by masaeedu** [comment]
+1

**Comment by MrHalfman** [comment]
Why do you want to install theses fonts on Windows?

Did you mean _How to install on Cygwin_?

**Comment by ehartford** [comment]
http://m.windowsitpro.com/scripting/trick-installing-fonts-vbscript-or-powershell-script

**Comment by ehartford** [comment]
https://github.com/powerline/fonts/pull/131

**Comment by GrmpCerber** [comment]
@ehartford thanks for pointing out #131 : it worked for me !!!
Yet I was expecting to read this info in the main `README.md` :(
