### ISSUE TITLE
fonts for powerline does not take any effects

### ISSUE THREAD

**Issue by ZhangHangCN** [powerline/fonts#133]
<img width="588" alt="2015-08-22 9 43 37" src="https://cloud.githubusercontent.com/assets/9375385/9424220/ec7810e4-4916-11e5-8fc4-a1069ea38702.png">
After installing oh-my-zsh, fonts for powerline seems  not take any effect. It is just like fonts with no powerline. Is there any wrong? Thanks

**Comment by giannigdev** [comment]
I Don't know if this is correlated to your case, but can you display correctly the  ? I am using the agnoster theme with oh-my-zsh and i have also installed this powerlinefonts but it doesn't seems to encode correctly that character.

![screen shot 2015-08-23 at 19 47 24](https://cloud.githubusercontent.com/assets/4886490/9438170/1e63aea6-4a5c-11e5-9ea3-12c0115ec4bc.png)

**Comment by giannigdev** [comment]
I have resolved choosing one of the Meslo fonts from Profiles -> Text in iTerm preferences.

**Comment by ZhangHangCN** [comment]
@giannigdev 
I have done the same as you did. But there seems no change. I wonder if there is something else wrong?

**Comment by mrmartineau** [comment]
When using iTerm, you need to set both the regular & non-ASCII font to your chosen Powerline font. See [here](https://www.dropbox.com/s/b94jv7s0xpqo440/Screenshot%202015-09-19%2018.57.48.png?dl=0)

**Comment by giannigdev** [comment]
yeah, i change both regular and non-ASCII font as @mrmartineau has said.

**Comment by Jerry-Lau** [comment]
@giannigdev  @mrmartineau  wow, change the font for both ASCI and non-ASCI text to Meslo solved the problem!

**Comment by ZhangHangCN** [comment]
@mrmartineau @giannnigdev
I have already set as both regular and non-ASCII font as you can see, but it seems take no affects

**Comment by ZhangHangCN** [comment]
I have found the reason that the theme of oh my zsh is not agnoster. After change this, everything is OK.Thx! @mrmartineau @giannigdev
