### ISSUE TITLE
Source Code Pro font files are incorrectly named "Sauce" Code Pro 

### ISSUE THREAD

**Issue by her** [powerline/fonts#135]
Hey all, 

You can see from my terminal what I am describing in my issue title. I haven't had a chance to look further into the .otf font files but I'm sure this could be an easy fix. If I get some extra time I'll check it out. 

<img width="966" alt="screen shot 2015-09-07 at 9 43 13 am" src="https://cloud.githubusercontent.com/assets/10278096/9718016/f11627d6-5545-11e5-912c-84e4e816607a.png">

**Comment by Lokaltog** [comment]
Most of the patched fonts are intentionally renamed due to license restrictions. See #46.
