### ISSUE TITLE
Consider Code New Roman

### ISSUE THREAD

**Issue by adriandeveloper** [powerline/fonts#138]
Very nice font I've found when I was browsing for new code fonts.  Code New Roman

http://www.dafont.com/code-new-roman.font

![screenshot 2015-09-19 11 45 45](https://cloud.githubusercontent.com/assets/3031275/9977189/264a8bfe-5ec4-11e5-9f33-e7e6378e17f5.png)

It looks nice especially in the terminal.  Can you guys patch this?

**Comment by kuznero** [comment]
Agree, it would be great!
Thanks in advance!
