### ISSUE TITLE
Make a release tarball of the fonts

### ISSUE THREAD

**Issue by Justinzobel** [powerline/fonts#151]
Please release a versioned tarball so these are easily packaged. Just in the releases section would do on GitHub :)

**Comment by Lokaltog** [comment]
Sure, why not. Tagged the current HEAD here: https://github.com/powerline/fonts/releases/tag/2015-12-04

**Comment by trevor-viljoen** [comment]
@Lokaltog Could a new release be tagged? We have some internal caching software that is able to pull from GitHub, but only tagged releases. As it currently stands, we can pull the 2015-12-04 release, but that doesn't include what's currently in master.
