### ISSUE TITLE
Arrows Missing with Inconsolata and Roboto Mono Medium

### ISSUE THREAD

**Issue by muraii** [powerline/fonts#161]
Hi there.

I have preserved my meandering post because someone else might have the same or a similar experience and maybe this will help.

I'm trying out an `oh my zsh` theme that depends on Powerline. I believe I've narrowed the reason for my difficulties (see screenshots below) to an issue with `powerline-status` finding `powerline-config` or a suitable proxy. When installing `powerline-status` I got no errors, so it doesn't _seem_ to be an issue with system Python vs. needing to install a different version (e.g., via `homebrew`). To be clear: I am using system Python 2.7.3 on OS X.

In lines 189-195 of `powerline.zsh` the script sets `POWERLINE_CONFIG_COMMAND` to one of two values:

- `powerline-config` : if `which` can find it; or
- a path to a `powerline-config` in a `scripts` directory.

Presuming this was a `$PATH` issue, I adjusted my `.zshrc` to point to the appropriate directory. Yet even though when _**I**_ evaluate `which powerline-config` it is found, `powerline.zsh` still won't:

![image](https://cloud.githubusercontent.com/assets/403865/13879211/a9566f16-ecec-11e5-8a71-48c194c07991.png)

Not sure if this is an _issue_ as much as PEBKAC but I'm a little lost. Anything jump out?

**OS**: OS X 10.10.5
**Python**: 2.7.3 in `/usr/bin/`
**Terminal**: Iterm2 2.1.4 (stable)
**Shell**: zsh 5.1.1 in _/us/local/bin/_ (from homebrew)
**Shell Theme**: wild-cherry

Danke!

[Original meandering below]

---

Hello! I'm trying out the `wild-cherry` theme for `oh my zsh` and am having one main issue. First: I've installed both the Inconsolata and Roboto Mono Medium patched fonts to try out, and chosen the latter in Iterm2. I installed via `pip install --user powerline-status` with no errors. Most things seem to work fine except for the arrows used for `SEGMENT_SEPARATOR`.

You'll see in this screenshot that the glyphs for the emojis work just fine, but the arrows don't nor does `u. I've been all through the documentation (of course, _everyone_ says this, but...) and can't find any step I'm missing. I've ensured Iterm2 is set to UTF-8 encoding, have had enough coffee, and have spoken in a clear, pleasant tone. All the good stuff.

![image](https://cloud.githubusercontent.com/assets/403865/13860953/40a9e4f6-ec61-11e5-9dbf-c5b0f0de60f6.png)

On some continued research for this post, I realize that despite apparently installing the fonts correctly, and selecting them in Iterm2, choosing one of these fonts or a non-patched font doesn't change the prompt. This suggests PEBKAC, but I'm not sure _how_. Executing `echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"` per the [docs for agnoster](https://gist.github.com/artdokxxx/4f2f49c03c3a0832799b#compatibility) neither `ue0b0` nor `ue0a0` seem present, but the others are. These are, of course, the segment-separating arrow and the git prefix branch.

![image](https://cloud.githubusercontent.com/assets/403865/13861435/c3be9114-ec63-11e5-9844-9265848adfd7.png)

**Comment by bweinand** [comment]
I had the same issue. I overlooked a setting in iTerm2. I had a standard font set for Non-ASCII Font. You have to uncheck 'Use a different font ...' or use the powerline font for the Non-ASCII Font too.

![2016-03-22_08-07-02](https://cloud.githubusercontent.com/assets/321488/13944393/4d5f975c-f005-11e5-90f8-6e6e367a3bfe.png)

**Comment by muraii** [comment]
Perfect. I looked at so many possible causes and completely overlooked that. All better. Cheerio!
