### ISSUE TITLE
Powerline Symbols showing <b0> (and others) instead of correct characters

### ISSUE THREAD

**Issue by austincrft** [powerline/fonts#169]
With `encoding=utf-8`
![image](https://cloud.githubusercontent.com/assets/3616544/14623881/6e9473a6-059b-11e6-8adf-55b90635aa98.png)

With `encoding=latin1`
![image](https://cloud.githubusercontent.com/assets/3616544/14623967/fbccce30-059b-11e6-955f-025f47fd2db4.png)

I get this issue using all of the fonts in this repo that I've tried. Running vim-airline on Windows 8.1 using the let `g:airline_powerline_fonts = 1` option. [This issue in the vim-airline repo](https://github.com/vim-airline/vim-airline/issues/820) claims it's a font issue. Do you agree?

**Comment by austincrft** [comment]
I actually had this same exact same issue using Arch Linux. It was because my locale encoding wasn't set up correctly. 

I assume there is some encoding issue I'm having in Windows, possibly related to locale. Wouldn't even know where to start looking.

Either way, the issue isn't with the fonts.

**Comment by nzbart** [comment]
@austincrft I know you resolved this a while ago, so your memory of the fix may be a bit hazy. I'm having this problem on Windows, but would be interested to see how you fixed the locale encoding issue on Linux in case I can try something similar.
