### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Swoorup** [powerline/fonts#174]
Could you please add a patched profont?

**Comment by AnwarShah** [comment]
Which profont? Do you have a link?

**Comment by Swoorup** [comment]
http://www.tobias-jung.de/seekingprofont/

**Comment by AnwarShah** [comment]
@Swoorup hi, I've patched this font. You can use it now or wait until it is merged. Good luck :)

**Comment by Swoorup** [comment]
Awesome thank you very much :100: :smiley:
