### ISSUE TITLE
"\ue0b0" not displaying properly on Ubuntu

### ISSUE THREAD

**Issue by julianorafael** [powerline/fonts#183]
When I run 
```
echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"
```
that's the output
```
 ±  ➦ ✘ ⚡ ⚙
```
Only the first character does not render properly. It should be a triangle pointed to right. What am I missing?

**Comment by julianorafael** [comment]
nvm, I just needed to change the font for one of those patched fonts.

**Comment by kb-fusus** [comment]
@frontendwizard I am facing the same issue. Could you share your solution?
