### ISSUE TITLE
Incorrect Source Code Pro Medium font's "Full name"

### ISSUE THREAD

**Issue by nelsyeung** [powerline/fonts#193]
The full name for the medium variant is incorrect `Source Code Pro Medium` instead of `Sauce Code Powerline Medium`:

<img width="736" alt="screen shot 2016-09-05 at 00 20 38" src="https://cloud.githubusercontent.com/assets/3951541/18234482/1d231776-72ff-11e6-950d-9f10af1dea3d.png">

This clashes with the original "Source Code Pro" font and it can confuse users. For example, under MacVim it requires you to set: `set gfn="Source Code Pro Medium"` instead of `set gfn="Source Code Pro for Powerline Medium"`.

Other variants have `Sauce Code Powerline $variant`:

<img width="725" alt="screen shot 2016-09-05 at 00 21 29" src="https://cloud.githubusercontent.com/assets/3951541/18234485/37b7ce1a-72ff-11e6-84aa-eb81388c562c.png">
To set this font I can set `set gfn="Source Code Pro for Powerline Light"`, which is expected.

The screenshots are from FontForge. This full name difference can also be seen from "Font Book" in mac.

Unfortunately I can't seem to generate fonts that can be installed using FontForge so I can't help with this problem. This seems to be easy to fix if one can tell me how these fonts are generated.

**Comment by AnwarShah** [comment]
I'll try to fix it. Looks like uniform naming is missing

**Comment by AnwarShah** [comment]
It should be resolved by now. Since the font is renamed to `Source Code Pro for Powerline`.  Please update the issue @nelsyeung

**Comment by nelsyeung** [comment]
It looks good. Thanks. 👍
