### ISSUE TITLE
Fira Mono (Fura Mono) has misaligned glyphs

### ISSUE THREAD

**Issue by hobarrera** [powerline/fonts#196]
Symbols are misaligned for "FuraMono-Regular Powerline". I tested this with `termite` and `st`.

![2016-10-03t03 28 14 330682802-03 00](https://cloud.githubusercontent.com/assets/730811/19029111/7bd63692-8919-11e6-83a2-aa9a260e4dec.png)

**Comment by hobarrera** [comment]
I decided to use it as-is until it's fixed, and immediately noticed that font-height is also messed up somehow.

Here's termite with Fira Mono, and Fira Mono for Powerline:
![Fira Mono](https://cloud.githubusercontent.com/assets/730811/19029574/d2e40df2-891d-11e6-8c34-e395aee0e205.png)

![Fira Mono for Powerline](https://cloud.githubusercontent.com/assets/730811/19029579/d826f978-891d-11e6-8666-b2d6c77ff824.png)

**Comment by hobarrera** [comment]
I ran `fontforge scripts/powerline-fontpatcher /usr/share/fonts/TTF/FiraMono-Regular.ttf` to generate the patched fonts myself. The resulting font doesn't have the line-height issue (second comment), but the misalignment issue (first comment) is slightly worse:

![2016-10-03t04 16 51 759101285-03 00](https://cloud.githubusercontent.com/assets/730811/19029867/3a5730b6-8920-11e6-8ba4-c16472d387b6.png)

**Comment by joetemp** [comment]
I have the same issue. Looks terrible. I tried using Fira Code and the alignment was fixed... but ligatures aren't supported in my terminal or editor (Termite and NeoVim). Please fix this alignment issue.

**Comment by JesseFarebro** [comment]
Same issue here with Fira Mono, my favorite font gets no love. I've tried it on urxvt and the same misalignment issue is happening.

**Comment by tripurari001** [comment]
same issue . i am using gnome terminal in ubuntu 16.04 . temporally using Roboto mono witch work fine

**Comment by tripurari001** [comment]
i added the powerline symbols in fira mono by myself and it  have no issue 
![screenshot from 2017-03-25 18-01-39](https://cloud.githubusercontent.com/assets/17466642/24322236/461c5096-1185-11e7-9509-898d508d9950.png)
![screenshot from 2017-03-25 18-02-21](https://cloud.githubusercontent.com/assets/17466642/24322237/461e2128-1185-11e7-97ef-936bc8be0cb2.png)



can i merge my font in this repo ?? is it ok to manipulate and share Fira Mono font ?

**Comment by ZyX-I** [comment]
@tripurari001 Yes on both. Do not forget to alter README (patched by part).

**Comment by tripurari001** [comment]
@ZyX-I  first let me tell you steps i followed to make this patch and if it is ok then i will make a merge request 

1. i downloaded  the font **Fira Mono**  from [Font Squirrel](https://www.fontsquirrel.com/fonts/fira-mono) 

2. downloaded the font **Fira Code** from [github repo](https://github.com/tonsky/FiraCode)

3. exported the 7 powerline symbol as svg from **Fira Code** using the tool [FontForge](https://fontforge.github.io/en-US/)

4. imported the 7 powerline symbol (svg file ) into **Fira Mono** and generated the **otf** font 

5. tested this font in my terminal ( plese see screenshot ) and this is working fine 

!important . i have only pached regular font (not bold and italic ) 

first time contributing to open-source and i don't want to mess anything   thats why making sure it is ok

**Comment by ZyX-I** [comment]
I actually never patched non-bitmap font myself. Though powerline symbols may be obtained from https://github.com/powerline/powerline/tree/master/font, it does not matter if you already did that.

If I am not mistaking, you normally are supposed to run the font patcher and fix the results if it appears to be misaligned (like now). Fontforge may fix, but I did not ever do this. If patching things the other way works fine it is fine though.

**Comment by ZyX-I** [comment]
Though note that on your screenshot from https://github.com/powerline/fonts/issues/196#issuecomment-289209023 you have ~<1px line between filled triangle and previous symbol, better visible with yellow one; and glyph should be a bit wider vertically. Still better then misaligned glyph though.

**Comment by tripurari001** [comment]
@ZyX-I  i tryed to make tingle wider but i can not because i have zero knowledge about font and i only did this for frist time because i wanted to use fira code in my terminal so badly 

even Fira code font have this little gap and shorter triangle so i thought this is the best one can achieve
 ( i don't know )  

and i also pached medium and bold font if you want i can make pull request now 

Thanks

**Comment by ZyX-I** [comment]
Can you show screenshots with variant that is already in the repository (regular, medium and bold) and your variant for comparison, with sizes 8, 12, 16?

**Comment by tripurari001** [comment]
@ZyX-I  sure

**Comment by tripurari001** [comment]
regular 13px
medium 13,11 px 
and bold 13,11px

os linux , ubuntu , Gnome terminal 

![bold-11-px](https://cloud.githubusercontent.com/assets/17466642/24349448/b9d1fdb0-12fc-11e7-940c-cd9d99d8e1cf.png)
![bold-13px](https://cloud.githubusercontent.com/assets/17466642/24349450/b9da60ae-12fc-11e7-8c5e-17d743f39180.png)
![medium-10px](https://cloud.githubusercontent.com/assets/17466642/24349451/b9ddd9e6-12fc-11e7-860d-5826ede9f3de.png)
![medium-13-px](https://cloud.githubusercontent.com/assets/17466642/24349452/b9e3b5aa-12fc-11e7-8bc8-8c45f38c0ad4.png)
![regular-13px](https://cloud.githubusercontent.com/assets/17466642/24349449/b9d58b56-12fc-11e7-9c17-c8e4d35c8ee5.png)

**Comment by ZyX-I** [comment]
Why only 13 and 11? This look fine though, better then what @hobarrera has.

**Comment by tripurari001** [comment]
@ZyX-I  because i am very lazy person  :) 

i hate doing repetitive task 

please wait for screen shot of old font  :)

**Comment by tripurari001** [comment]
current font  in repo 
bold 13,11px 
regular 11px
![bold-11-px](https://cloud.githubusercontent.com/assets/17466642/24350286/4568e3a0-12ff-11e7-9e9d-ccb487ea605e.png)
![bold-13-px](https://cloud.githubusercontent.com/assets/17466642/24350287/456c89ce-12ff-11e7-923b-d873413bde91.png)
![regular-11-px](https://cloud.githubusercontent.com/assets/17466642/24350288/4571cc40-12ff-11e7-9bc3-60bd33c3b503.png)

**Comment by tripurari001** [comment]
please note one more thing that 

after installation current font showing  **Fira Mono for powerline Regular**

and my pached font showing **Fira Mono Regular**

**Comment by ZyX-I** [comment]
You need to change name. Fontforge I have allows doing this in `<C-S-f>` (Element -> Font info).

**Comment by tripurari001** [comment]
@ZyX-I  done
