### ISSUE TITLE
Go Mono

### ISSUE THREAD

**Issue by itsjamie** [powerline/fonts#203]
I would love to see Powerline support added to this font.

https://blog.golang.org/go-fonts

Getting the font: 
```
If you just want the TTF files, run
git clone https://go.googlesource.com/image
and copy them from the subsequent image/font/gofont/ttfs directory
```

**Comment by JesseObrien** [comment]
Already have a pull request up here for it, just awaiting the merge :)

https://github.com/powerline/fonts/pull/200

**Comment by AnwarShah** [comment]
Go mono has been added.

**Comment by itsjamie** [comment]
Thank you!
