### ISSUE TITLE
Terminus does not install on Ubuntu

### ISSUE THREAD

**Issue by Industrial** [powerline/fonts#210]
Hi!

Using the ./install.sh (and it says it went fine) the Terminus for Powerline font does not install. This is my favorite font to code in, and I'd love to get it to work with Powerline (and tmux).

All the other fonts do get installed and I can pick them in the terminal.

gr,

Tom

**Comment by arijoon** [comment]
Have  you followed the `fontconfig` step at the bottom of the `README`?

**Comment by termNinja** [comment]
I also have the same problem with Terminus font, it's not showing anywhere.
I've moved config file where you've wrote.

https://image.ibb.co/jyB6TQ/terminess_Issue.png
https://image.ibb.co/g9CD8Q/terminess_Issue2.png

**Comment by arijoon** [comment]
@termNinja Did you rerun `fc-cache -vf` after copying the file?

**Comment by termNinja** [comment]
@arijoon  Yes, multiple times. Restarted my PC also and tried search for the font in multiple programs, still not there.

Here's the output of fc-cache -vf
https://pastebin.com/hTn4dciv

**Comment by termNinja** [comment]
I just want to confim that I've fixed my issue. By default bitmap fonts were disabled on Ubuntu. I've followed the instruction on [this](https://superuser.com/questions/886023/linux-mint-installing-bdf-fonts-with-console-fc-cache-fc-list) link and it solved my issue.

Cheers!

**Comment by Industrial** [comment]
I can confirm that this works. Thanks for the help :-)
