### ISSUE TITLE
Consolas font for powerline

### ISSUE THREAD

**Issue by xardael** [powerline/fonts#213]
As a feature request, could I ask for the Consolas font to be added? I found some versions here:
https://github.com/runsisi/consolas-font-for-powerline
https://github.com/eugeii/consolas-powerline-vim 

But 'GEAR' (U+2699) and 'HIGH VOLTAGE SIGN' (U+26A1) are not included.

Thank you.

**Comment by ZyX-I** [comment]
If I am not mistaking, license does not allow this.
