### ISSUE TITLE
Terminess missing special characters

### ISSUE THREAD

**Issue by andykais** [powerline/fonts#215]
in vim (nerdtree-git-plugin) and zsh (agnoster) theme showing git status
●
✗
✭
all these characters (and any others from this set of characters) appear as empty spaces. Is it possible they are missing from the Terminess font package or am I missing something in my font config?

.Xresources.d/fonts:
```
xterm*faceName: xos4 Terminess Powerline
xterm*faceSize: 9
```

```bash
$  fc-list | ag Term
/home/andrew/.local/share/fonts/ter-powerline-x16b.pcf.gz: xos4 Terminess Powerline:style=Bold
/home/andrew/.local/share/fonts/ter-powerline-x24b.pcf.gz: xos4 Terminess Powerline:style=Bold
/home/andrew/.local/share/fonts/ter-powerline-x14b.pcf.gz: xos4 Terminess Powerline:style=Bold
/home/andrew/.local/share/fonts/ter-powerline-x32b.pcf.gz: xos4 Terminess Powerline:style=Bold
/home/andrew/.local/share/fonts/ter-powerline-x22b.pcf.gz: xos4 Terminess Powerline:style=Bold
/home/andrew/.local/share/fonts/ter-powerline-x12b.pcf.gz: xos4 Terminess Powerline:style=Bold
/home/andrew/.local/share/fonts/ter-powerline-x28n.pcf.gz: xos4 Terminess Powerline:style=Regular
/home/andrew/.local/share/fonts/ter-powerline-x20n.pcf.gz: xos4 Terminess Powerline:style=Regular
/home/andrew/.local/share/fonts/ter-powerline-x28b.pcf.gz: xos4 Terminess Powerline:style=Bold
/home/andrew/.local/share/fonts/ter-powerline-x18n.pcf.gz: xos4 Terminess Powerline:style=Regular
/home/andrew/.local/share/fonts/ter-powerline-x20b.pcf.gz: xos4 Terminess Powerline:style=Bold
/home/andrew/.local/share/fonts/ter-powerline-x18b.pcf.gz: xos4 Terminess Powerline:style=Bold
/home/andrew/.local/share/fonts/ter-powerline-x32n.pcf.gz: xos4 Terminess Powerline:style=Regular
/home/andrew/.local/share/fonts/ter-powerline-x22n.pcf.gz: xos4 Terminess Powerline:style=Regular
/home/andrew/.local/share/fonts/ter-powerline-x12n.pcf.gz: xos4 Terminess Powerline:style=Regular
/home/andrew/.local/share/fonts/ter-powerline-x24n.pcf.gz: xos4 Terminess Powerline:style=Regular
/home/andrew/.local/share/fonts/ter-powerline-x14n.pcf.gz: xos4 Terminess Powerline:style=Regular
/home/andrew/.local/share/fonts/ter-powerline-x16n.pcf.gz: xos4 Terminess Powerline:style=Regular
```

**Comment by ZyX-I** [comment]
These characters are not part of the PowerlineSymbols font. We are not fixing such misses, ask upstream.

**Comment by ZyX-I** [comment]
Though terminus version is outdated, would need to repatch… or rather delete font from the repository: 4.39 changelog shows “Added the powerline characters E0A0..E0A2 and E0B0..E0B3.”

**Comment by andykais** [comment]
ok cool that they included powerline now but I am wondering about those icons I have listed, can you direct me in any way on how to patch the Terminess Powerline font with those fonts?

**Comment by ZyX-I** [comment]
@andykais I just converted font to txt format (see README in https://bitbucket.org/ZyX_I/bitmap-font-patcher), it is pretty straightforward text format you can even patch by hand. BDF format is also text, but not the kind you can easily edit by hand. Fontpatcher at link may only be reused if you refactor it a bit or create PowerlineSymbols.otf font where you copy just new glyphs.
