### ISSUE TITLE
Fonts do not work in tty

### ISSUE THREAD

**Issue by meepcode** [powerline/fonts#242]
The fonts work perfectly in X, however, they do not work in a tty.  I prefer to work in a tty, so any help will be appreciated.  When I try to set the font in a tty to one of these fonts it returns an error message of "Couldn't get a file descriptor referring to the console".  Sadly I cannot post any photos as it is a tty.

**Comment by ZyX-I** [comment]
Aside from terminus no fonts here are supposed to work in a built-in kernel terminal: this one is limited to simple bitmap font, AFAIK with at most 512 (or some other power of two) glyphs in them. You may have some luck with fbterm which is supposed to work on top of the kernel framebuffer and actually do use font rendering libraries, but my experience tells that fbterm may or may not mess up the glyphs from run to run.

And if you are using framebuffer there is `fbgrab` for taking screenshots. Though for VGA console the only easy option is taking a photo (uneasy would be perform MitM attack on the cable connecting video card and screen which needs special hardware, maybe there is also a way to take image directly from video card in this case, but I do not know).

**Comment by ZyX-I** [comment]
(Note: while there is terminus in necessary format, it is not installed by the script.)
