### ISSUE TITLE
For Hyper.app users…

### ISSUE THREAD

**Issue by svinkle** [powerline/fonts#244]
Just a quick note: If you're using [Hyper terminal](https://hyper.is/) you might need to adjust the `fontFamily:` property in your `~/.hyper.js` config file for the font to show up:
```javascript
// font family with optional fallbacks
fontFamily: '"Meslo LG S for Powerline", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
```

**Comment by ametthey** [comment]
Thanks a lot ! Worked **perfectly** for me ! 👍 👍
