### ISSUE TITLE
Clock glyph too much tiny and barely visible

### ISSUE THREAD

**Issue by ricpelo** [powerline/fonts#247]
Using powerline 2.3 on Ubuntu 16.04 LTS and tmux 2.1 with Liberation Mono for Powerline Regular 13 pt.

The clock glyph that shows near the clock time is too much tiny and barely visible (and it seems to "float" up, like a superscript). I remember some time ago the clock looked perfectly.

![2017-09-04-192336_1280x1024_scrot](https://user-images.githubusercontent.com/616169/30035122-fe11700e-91a6-11e7-8fb7-61ee49ca8e50.png)

**Comment by ZyX-I** [comment]
Clock and other glyphs present in the main unicode range are not maintained here: font patchers only add powerline-specific glyphs to private use area, everything else is expected to be present in the font or taken from the fallback. Default top_theme contains only powerline and glyphs that are present in terminus font for this reason (BTW, *not including* clock glyph, you most likely use non-default `powerline` theme).

**Comment by ZyX-I** [comment]
What happened since “some time ago” is most likely that something (e.g. installing or removing some font during update) added more preferred fallback font: this exact clock glyph was a main reason `powerline_terminus` top_theme was created and made default: it is rarely present in all used fonts.
