### ISSUE TITLE
Strange Symbols in power line 

### ISSUE THREAD

**Issue by matze9194** [powerline/fonts#252]
<img width="789" alt="issue" src="https://user-images.githubusercontent.com/24566968/30882759-58297072-a30a-11e7-95ec-8bcd4810102b.png">

Has anyone a suggestion for the red lines in the pictures ??
 It is not supposed that "Big Bang" an "64?" is standing there.

**Comment by ZyX-I** [comment]
Why are you asking that in powerline/fonts, it has nothing to do with fonts? If you were using powerline you need to ask in its mailing list mentioned in https://github.com/powerline/powerline README, but I highly doubt you actually are: this picture is only possible with custom configuration and if you did create custom configuration then you would for sure know what you put there.
