### ISSUE TITLE
Strange symbol display problem in vim

### ISSUE THREAD

**Issue by agulas** [powerline/fonts#261]
I installed vim 8.0 and vim-airline and powerline fonts yesterday. Everything works fine in bash shell. 
But when I installed zsh and oh-my-zsh today, something strange happened. Powerline font works fine in zsh shell, but in vim those symbols are gone. 
![image](https://user-images.githubusercontent.com/3980422/33937302-e48a9b8e-e03d-11e7-94a9-78193adadb9f.png)
![snipaste_2017-12-13_19-39-24](https://user-images.githubusercontent.com/3980422/33937218-8fa4c496-e03d-11e7-8a95-709477e21008.png)
Here's the stranger things: if I change my shell to bash and then change back to zsh, everything's back to normal.
![image](https://user-images.githubusercontent.com/3980422/33937048-d461ddb8-e03c-11e7-885d-84161de23c71.png)
I'm using windows 7 and Xshell5 to login a server runing centos 4.3.
Please tell me what went wrong. Thank u guys!

**Comment by ZyX-I** [comment]
You need to check the difference in `env` output between the valid and invalid shell calls, you have some environment set up incorrectly.

**Comment by agulas** [comment]
I find out why. zsh env is different from bash env. After I fix it, everything's ok now.
