### ISSUE TITLE
windows install script error

### ISSUE THREAD

**Issue by wby238** [powerline/fonts#267]
OS:x64 win7,
log:
```log
F:\git\fonts>Powershell.exe -executionpolicy remotesigned -File install.ps1
命名参数后缺少“=”运算符。(tr:Missing "=" operator after named parameters)
所在位置 F:\git\fonts\install.ps1:18 字符: 38
+ [CmdletBinding(SupportsShouldProcess) <<<< ]
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEqualsInNamedArgument
```

**Comment by hongliang5316** [comment]
@wby238 
I have the same problem.
Do you solve this?

**Comment by wby238** [comment]
@hongliang5316
No, so I choose to install part of them instead of all. And now it works well.

**Comment by hongliang5316** [comment]
@wby238 
Hello, I had solved this problem.
Because of the default version of `PowerShell` was too lower on Windows7, you can upgrade your powershell version to solve this.
See https://www.microsoft.com/en-us/download/details.aspx?id=54616
Good Luck!

**Comment by zrss** [comment]
thx @hongliang5316, nice catch

**Comment by hunter199129** [comment]
I had this problem, too. I solved it by modifying the script to
 
    [CmdletBinding(SupportsShouldProcess = $true)]

then it's working.

**Comment by longhaiqwe** [comment]
@hunter199129 work! Thanks
