### ISSUE TITLE
Pull request to add Cousine Powerline

### ISSUE THREAD

**Issue by revolutionnaire** [powerline/fonts#271]
I've already created  branch on a local copy of the repository. I also made the necessary changes: add fonts, modified `PowerlineFonts.css`, `README.md`, and `preview.html`.

It just won't allow me to push the branch. It gives me this error:
```
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by revolutionnaire** [comment]
Oops! Sorry, wrong repository.

**Comment by thedonquixotic** [comment]
@revolutionnaire If this issue is done, would probably be a good idea to close this issue to improve the noise to signal ratio in the open tickets.

**Comment by revolutionnaire** [comment]
Sorry about the delay.
