### ISSUE TITLE
Fontconfig warning on install

### ISSUE THREAD

**Issue by tejasbubane** [powerline/fonts#273]
I received this fontconfig warning while installing the fonts:

```
➜ ./install.sh
Copying fonts...
Resetting font cache, this may take a moment...
Fontconfig warning: line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf

Powerline fonts installed to .....
```

The installation was successful, but just wanted to bring the warning to your notice.

**Comment by ZyX-I** [comment]
`install.sh` does not mess with any configuration files, just copying files over and running fc-cache, it is entirely *your* warning to fix.
