### ISSUE TITLE
sudo apt install zsh doesn't seem to work

### ISSUE THREAD

**Issue by jamesray1** [powerline/fonts#274]
```
james@james-Streacom:~$ sudo apt-get install fonts-powerline
Reading package lists... Done
Building dependency tree       
Reading state information... Done
fonts-powerline is already the newest version (2.5-1.1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

Powerline fonts show up in custom fonts in profile preferences in Bash and UTF-8 is enabled as an encoding. With Powerline Symbols Medium enabled as a font I still get the same output:
```
james@james-Streacom:~$ echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"
\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699
```

**Comment by fulldecent** [comment]
What's your term emulator stack?

I suppose you are Ubuntu / Gnome Terminal?

**Comment by jamesray1** [comment]
```
james@james-Streacom:~$ echo $TERM
xterm-256color
```

Yep, Ubuntu 17.10, Gnome. Let me k

**Comment by jamesray1** [comment]
I got it to work. I just removed the .om-my-zsh folder that was installed from `sudo apt install zsh` and then ran `sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"` as per the readme. Then:
```
➜  ~ echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"
 ±  ➦ ✘ ⚡ ⚙
```
