### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by nitin-jotwani** [powerline/fonts#276]
`Unable to locate package fonts-powerline` Using Ubuntu 14.04

**Comment by ZyX-I** [comment]
Ubuntu packages are not maintained here. Based on https://packages.ubuntu.com/search?keywords=fonts-powerline&searchon=names&suite=all&section=all it looks like it is in official distribution only since 16.04 and was probably in PPAs before. Do not know which PPAs though.

**Comment by nitin-jotwani** [comment]
`update` 
follow this if unable to install, https://gist.github.com/renshuki/3cf3de6e7f00fa7e744a
