### ISSUE TITLE
After installing fonts-powerline the fonts are changed

### ISSUE THREAD

**Issue by Tsadoq** [powerline/fonts#290]
So, I installed fonts-powerline to be able to use the oh-my-zsh theme (agnoster) but after installing them i still see the "empty squares" because clearly the font was not changed. I'm currently using debian, i3 and xterm. Checking "grep -i "fontface" /etc/default/console-setup" tells me "fontface=fixed". I get that probably i'm doing something wrong but i'm unable to understand what. Thank you very much

**Comment by Krzysiu** [comment]
They doesn't replace fonts, but they install new, with suffix "for powerline-shell". So you need to change them at first.
