### ISSUE TITLE
More info for SVN VCS

### ISSUE THREAD

**Issue by fniessen** [powerline/fonts#298]
Hi and thanks a lot for this wonderful piece of art!

I'm switching from Agnoster to this, as it offers all from it, and even more, except for one stuff: the info shown for a SVN repo.

I got this working in Agnoster (copied from somewhere):

    if [ -r "$ZSH" ]; then
        prompt_svn() {
            local rev branch
            if in_svn; then
                rev=$(svn_get_rev_nr)
                branch=$(svn_get_branch_name)
                if [[ $(svn_dirty_choose_pwd 1 0) -eq 1 ]]; then
                    prompt_segment yellow black
                    echo -n "$rev@$branch"
                    echo -n " ±"
                else
                    prompt_segment green black
                    echo -n "$rev@$branch"
                fi
            fi
        }
    fi

How can it be adapted for Powerlevel9k?

Thanks again!

**Comment by ZyX-I** [comment]
This repository contains only *fonts*. Nothing else is maintained here. Powerlevel9k has its own repository on github.
