### ISSUE TITLE
Please patch Cascadia Code

### ISSUE THREAD

**Issue by asankah** [powerline/fonts#322]
Repo is at https://github.com/microsoft/cascadia-code

**Comment by willem640** [comment]
https://github.com/powerline/fontpatcher

**Comment by willem640** [comment]
needs fontforge w/ python bindings,
with the font patcher you can do it yourself

**Comment by Losses** [comment]
@asankah Try this: https://github.com/AaronFriel/nerd-fonts/releases/tag/v1.2.0

**Comment by asankah** [comment]
Thanks!

I'll close this issue since the patched font is available.
