### ISSUE TITLE
What's the relationship with powerline/powerline ?

### ISSUE THREAD

**Issue by PMExtra** [powerline/fonts#324]
Is this repo a pre-built binary release of [powerline/powerline](https://github.com/powerline/powerline)?

Why does this repo have no updated with the source? I saw the source have 19 releases and the latest version is 2.7 that released at Aug 2018. But this repo have only one release that released at Dec 2015.

**Comment by BlitzKraft** [comment]
This repo provides only the fonts, not the powerline program or binary.
