### ISSUE TITLE
whats the meaning of DZ?

### ISSUE THREAD

**Issue by cmdedj** [powerline/fonts#335]

**Comment by ChiefMikeK** [comment]
- [In weather maps, meteorological symbol for _drizzle_ ](https://en.wikipedia.org/wiki/DZ#In_science_and_technology)
- 👓  also [DZ - Wiktionary](https://en.m.wiktionary.org/wiki/DZ)

**Comment by HooSing** [comment]
which DZ?

**Comment by cmdedj** [comment]
> which DZ?

such as that 

Meslo LG M DZ Regular for Powerline.ttf

**Comment by jasonk** [comment]
DZ means "Dotted Zero", indicating that a zero is differentiated from a capital-o by having a dot in the middle, as opposed to SZ or "Slashed Zero"

**Comment by cmdedj** [comment]
> DZ means "Dotted Zero", indicating that a zero is differentiated from a capital-o by having a dot in the middle, as opposed to SZ or "Slashed Zero"

thank you very much
