### ISSUE TITLE
Add JetBrains Mono for Powerline

### ISSUE THREAD

**Issue by seanghay** [powerline/fonts#336]
JetBrains has just released a new open-source font called [JetBrains Mono](https://github.com/JetBrains/JetBrainsMono).  

![image](https://user-images.githubusercontent.com/15277233/72458698-a737ea80-37fb-11ea-91bc-d81fbd860c52.png)

**Comment by seanghay** [comment]
Here is my version of patched [JetBrains Mono for Powerline](https://github.com/seanghay/JetBrainsMono-Powerline). In case you want to use it.

**Comment by dagadbm** [comment]
yes!

**Comment by testing-in-chrome** [comment]
+1

**Comment by wyhasany** [comment]
@seanghay could you add non-ascii characters available here?
https://github.com/Falkor/dotfiles/blob/master/fonts/SourceCodePro%2BPowerline%2BAwesome%2BRegular.ttf

**Comment by seanghay** [comment]
> @seanghay could you add non-ascii characters available here?
> [Falkor/dotfiles:fonts/SourceCodePro%2BPowerline%2BAwesome%2BRegular.ttf@`master`](https://github.com/Falkor/dotfiles/blob/master/fonts/SourceCodePro%2BPowerline%2BAwesome%2BRegular.ttf) [](/Falkor/dotfiles/blob/HEAD@{2020-01-25T18:49:19Z}/fonts/SourceCodePro%2BPowerline%2BAwesome%2BRegular.ttf)

I really have no idea on how to do that.

**Comment by GenesisTMS** [comment]
It can be done without patching the font using fontconfig [substitude](https://fedoraproject.org/wiki/Fontconfig_packaging_tips#Font_substitution). 
I am on Fedora.

I am using JetBrains Mono and whenever cannot find symbol try to find it in Hack font (or whatever you want to substitude for).

My fontconfig in `$HOME/.config/fontconfig/conf.d` folder
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "../fonts.dtd">
<fontconfig>
	<!-- SUBSTITUDE -->
	<alias binding="same">
		<family>Hack</family>
		<accept>
			<family>JetBrains Mono</family>
		</accept>
	</alias>
</fontconfig>
```

**Comment by jmigual** [comment]
Hey, I submitted a PR with that, it's in #337

**Comment by mserajnik** [comment]
JetBrains Mono has had official Powerline support since [v1.0.2](https://github.com/JetBrains/JetBrainsMono/releases/tag/v1.0.2).

**Comment by dagadbm** [comment]
Does that mean i dont need the nerd font anymore?

**Comment by mserajnik** [comment]
> Does that mean i dont need the nerd font anymore?

The official version has been working fine for me. I only found out about it a week or so ago myself.

I was maintaining a PKGBUILD of seanghay's patched font in the AUR (user repository for Arch Linux packages) before before but had it removed after someone notified me that Powerline support has been official since v1.0.2.

**Comment by seanghay** [comment]
> JetBrains Mono has had official Powerline support since [v1.0.2](https://github.com/JetBrains/JetBrainsMono/releases/tag/v1.0.2).

Coooool!
