### ISSUE TITLE
Partial install

### ISSUE THREAD

**Issue by fcpauldiaz** [powerline/fonts#369]
I'm using Hyper.js with agnoster theme and the powerline fonts are working partially, any idea what I'm missing ? OSX 11.5.2 

![Screen Shot 2021-09-10 at 11 20 58](https://user-images.githubusercontent.com/4523284/132877645-f094b209-83c8-4279-986e-314e33f02709.png)

**Comment by hnnhpark** [comment]
same here... 😢

**Comment by mp3846** [comment]
Bothers me as well

**Comment by fcpauldiaz** [comment]
I fixed this issue by fixing my Hyper.js config. I had some invalid apostrophes characters in my config  that looked like valid ones, like this: ‘stable’. I replaced them all and it was fixed. Problem was not related to powerline fonts
