### ISSUE TITLE
Unable to install / use on macOS Sequoia (Dev Beta 2) ? 🤔

### ISSUE THREAD

**Issue by DavidGarciaCat** [powerline/fonts#401]
I have followed the `Quick Installation` steps from the [readme](https://github.com/powerline/fonts?tab=readme-ov-file#quick-installation) file:

```
 david@macbookpro  ~  git clone https://github.com/powerline/fonts.git --depth=1
Cloning into 'fonts'...
remote: Enumerating objects: 317, done.
remote: Counting objects: 100% (317/317), done.
remote: Compressing objects: 100% (245/245), done.
remote: Total 317 (delta 73), reused 260 (delta 69), pack-reused 0
Receiving objects: 100% (317/317), 10.74 MiB | 18.26 MiB/s, done.
Resolving deltas: 100% (73/73), done.
 david@macbookpro  ~  cd fonts
 david@macbookpro  ~/fonts   master  ./install.sh
Copying fonts...
Powerline fonts installed to /Users/david/Library/Fonts
 david@macbookpro  ~/fonts   master  cd ..
 david@macbookpro  ~  rm -rf fonts
 david@macbookpro  ~ 
```

After closing my terminal and open it again, I still cannot see the fonts I should see when installing the [**agnoster** theme](https://github.com/agnoster/agnoster-zsh-theme) for ohmyzsh

I can confirm it was working with macOS Sonoma, but it doesn't work anymore with macOS Sequoia (Dev Beta 2)

**Comment by jiapengjun** [comment]
Meet the same issue.  MacOS 15.0

**Comment by hulto** [comment]
-Bumping this - I'm also having this issue.-

Nevermind just user error 🫠 
Make sure your terminal using using a powerline enabled font.
Terminal > Settings
<img width="277" alt="image" src="https://github.com/user-attachments/assets/6a262603-bc43-49c9-8da1-9aff88048d08">

Profiles > Text > Font > Choose a powerline enabled one.
<img width="681" alt="image" src="https://github.com/user-attachments/assets/d0af3bd9-3167-4fee-b434-8c3261114a9f">

**Comment by DavidGarciaCat** [comment]
The suggestion above solves the issue.
