### ISSUE TITLE
Fancy Symbols not working in MacVim

### ISSUE THREAD

**Issue by philrhinehart** [powerline/fonts#59]
I have installed the Source Code Pro for Powerline font in Font Book (downloaded pre-patched version), and added to .vimrc file, however I cannot get the symbols to work. I have also tried patching the fonts myself, other pre-patched fonts and modifying every related setting I could think of... with no results. (Running os x 10.9.1)

Am I missing something?

<code>set encoding=utf-8</code>
<code>set guifont=Source\ Code\ Pro\ for\ Powerline</code>
<code>let g:Powerline_symbols = 'fancy'</code>

![image](https://f.cloud.github.com/assets/4663636/1897478/d8328466-7be5-11e3-99e8-b1da7ac5c2fa.png)

**Comment by elyezer** [comment]
`set guifont=Source\ Code\ Pro\ for\ Powerline` does the trick

**Comment by RoyLING** [comment]
`set guifont=Sauce_Code_Powerline:h11` with patched font.
