### ISSUE TITLE
Fancy symbols several pixels larger than it should be

### ISSUE THREAD

**Issue by timfeirg** [powerline/fonts#70]
I installed powerline symbols and [Patched Anonymous Pro](https://github.com/Lokaltog/powerline-fonts/tree/master/AnonymousPro) according to [the official guide](https://powerline.readthedocs.org/en/latest/installation/linux.html#font-installation) and the actual effect is awesome, but the symbols looks a little bigger than it should be:

![image](https://cloud.githubusercontent.com/assets/4319104/3549605/159bf922-08cc-11e4-9fe0-beb51bbdfc7c.png)

believe me I've properly set font and font size in iterm2 settings, I also tried to set non-ASCIIs smaller but they just don't fit together. I feel like an asshole posting something something like this but it's agonizing for me to see something like this.

**Comment by hoodslide** [comment]
This could be considered a "feature", except that it causes rendering problems when resizing windows. So, a bug then.

![screen shot](https://cloud.githubusercontent.com/assets/601124/8416057/9c4bf050-1e68-11e5-9199-dfbcbb0563b1.png)
