### ISSUE TITLE
Is there anywhere to see examples of each of the fonts?

### ISSUE THREAD

**Issue by Sequoia** [powerline/fonts#97]
This would be very helpful for a new user like me. :smile:

**Comment by nchammas** [comment]
:+1: This would help people pick a font they like quickly.

**Comment by bucaran** [comment]
:+1:

**Comment by shnode** [comment]
![image](https://cloud.githubusercontent.com/assets/7784713/7021245/524161ae-dd52-11e4-8d52-e7cc87230ad7.png)
