### ISSUE TITLE
[License] Can I download via script and install? 

### ISSUE THREAD

**Issue by bucaran** [powerline/fonts#99]
I see the licenses vary a bit among fonts. Probably not a issue, but I would like to make sure I am allowed to create a script that downloads the fonts in this repository and installs them on my Mac?

**Comment by Lokaltog** [comment]
That shouldn't be a problem, the licences don't limit your ability to mass download all the fonts, but they affect what you're allowed to do with the fonts yourself (i.e. if you want to share them after modifying them, etc.)

**Comment by bucaran** [comment]
I see. I don't plan modifying them, just automate the process of downloading the repo, and installing them on my mac on a larger [script](https://git.io/getdarwin) I wrote.

**Comment by Lokaltog** [comment]
That should be totally fine. The mass download functionality is already provided for other OSes through e.g. package managers.

**Comment by bucaran** [comment]
I use homebrew and cask, what would the be package name be? It would save me some typing.

**Comment by Lokaltog** [comment]
I'm not sure if there are any packages available for either of those.

**Comment by bucaran** [comment]
Well, there is already `install.sh`, which I should be able to easily customize for my needs. It's basically, just dropping the font files inside `~/Library/Fonts` on OS X.
